# Generated by Django 3.0.8 on 2020-07-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dothings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(choices=[('before 9', 'before 9'), ('after 9 but before 12', 'after 9 but before 12'), ('after 12 but before 3', 'after 12 but before 3'), ('after 3 but before 9', 'after 3 but before 9')])),
            ],
        ),
    ]
