# Generated by Django 3.0.8 on 2020-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dowork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dothings',
            name='due_time',
            field=models.CharField(choices=[('before 9', 'before 9'), ('after 9 but before 12', 'after 9 but before 12'), ('after 12 but before 3', 'after 12 but before 3'), ('after 3 but before 9', 'after 3 but before 9')], max_length=64),
        ),
    ]
