# Generated by Django 3.0.8 on 2020-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dowork', '0002_auto_20200705_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dothings',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
