# Generated by Django 3.0.8 on 2020-07-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dowork', '0003_auto_20200705_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='dothings',
            name='done',
            field=models.CharField(default='false', max_length=64),
        ),
    ]
