# Generated by Django 3.0.8 on 2020-07-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dowork', '0004_dothings_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dothings',
            old_name='done',
            new_name='donetask',
        ),
    ]
