# Generated by Django 3.0.8 on 2020-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dowork', '0006_auto_20200706_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dothings',
            name='due_date',
            field=models.DateField(),
        ),
    ]
