# Generated by Django 3.0.8 on 2020-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dowork', '0007_auto_20200706_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dothings',
            name='due_time',
        ),
        migrations.AlterField(
            model_name='dothings',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
