# Generated by Django 3.0.8 on 2020-07-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dowork', '0008_auto_20200706_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dothings',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
