# Generated by Django 3.0.8 on 2020-07-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dowork', '0009_auto_20200706_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='dothings',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
